### ISSUE TITLE
Verbesserung der Tooltips bei Punkteingabe

### ISSUE THREAD

**Issue by schmittwilken** [maikmerten/vit-klausurrechner#4]
Da die Nummerierung der Aufgaben in der Klausur vom Schema 1, 2, 3 ... aufgrund von Unteraufgaben (1a, 1b) abweichen kann, wäre es hilfreich, die Tooltips in der Tabelle zur Eingabe der Punkte aussagekräftiger zu machen.

Hier könnte der Kommtar der Aufgaben angefügt werden, in dem dann die Eigenschaft der Unteraufgabe näher beschrieben wird (Zeile 198):

`td = $("<td title='Aufgabe " + key + (aufgabe.getIsMC() ? " (Multiple-Choice)" : " (Textaufgabe)") + ": " + aufgabe.getKommentar() + "'>");`

**Comment by maikmerten** [comment]
Ist umgesetzt!
